### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by panky00** [jamiecaesar/securecrt-tools#35]
Hello, 
I am fairly new to scripting. I wanted to test your scripts on Secure CRT. But I am getting folloiwng error.

Error 'SecureCRT.Application' obkect has no attribute 'ScriptFullName' Line 10
script_dir, script_name = os.path.split(crt.ScriptFullName)

**Comment by jamiecaesar** [comment]
Can you tell me which version of SecureCRT are you using?
