### ISSUE TITLE
Help with s_arp_to_csv

### ISSUE THREAD

**Issue by aegcni81** [jamiecaesar/securecrt-tools#43]
Hello.

First of all, I want to thank you for sharing this incredible jewel. I has help me a lot with my daily job. I'm trying to run the script called **s_arp_to_csv.py** and is getting me the following error when using VRF:

**Error: 'CRTScript' object has no attribute 'hostname'
Line: 70**

With the global or default table, is working as expect.

Thank you again.

Best regards.

**Comment by jamiecaesar** [comment]
Thanks for the feedback and I'm glad you are finding the scripts useful.

That problem is fixed now if you update your repo (or just download the latest version of that script).  I pushed a few other minor fixes as well, so may not hurt to just update everything.
