### ISSUE TITLE
Additional Feature Request in switchport mapping script

### ISSUE THREAD

**Issue by cmacasae** [jamiecaesar/securecrt-tools#46]
As a network engineer I find the collection of scripts very useful. Kudos!

However, in the switchport mapping script it will useful for me as a network engineer if there are also columns for speed, duplex, and type (the ones found in the show interface status command). It seem those were dropped by the script. It will be nice to have those back please :-}

Another add-on if cdp neighbor table can also be added to the switchport mapping script.

Thank you for these amazing scripts.

**Comment by jamiecaesar** [comment]
Please pull the devel branch and see if the script work correctly for you (note: you'll need to pull all the changes in the devel branch, not just the one script because I had to make some changes elsewhere)

**Comment by cmacasae** [comment]
will check today jamie. thank you for taking time on my request.

**Comment by jamiecaesar** [comment]
Did the updated script meet your needs?  If so, I'll close the issue.

**Comment by cmacasae** [comment]
Yes. Thank you very much.
