### ISSUE TITLE
multi-command capture

### ISSUE THREAD

**Issue by cmacasae** [jamiecaesar/securecrt-tools#48]
It would be very useful to also have a script that reads a user-defined text file for a list of commands that it can execute in a current connected device. Both in exec, global, interface modes and others.

**Comment by jamiecaesar** [comment]
I believe the document_device script already does what you are requesting.  You can provide a custom list of commands, or just modify the per-OS lists in the settings.ini file and it will capture all of those commands for any device you run it on.   There is also a multi-device version if you wanted to capture the same list of commands over a bunch of devices at once.

**Comment by cmacasae** [comment]
I will check that out. Thank you very much
